[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "9bqQoWC9ovH3FFGzEAV2MJJkF1uNuS4EVGZ2SmRw17w8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/tushar/bound-market-core/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/position.ts"
